// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCombosFolder():Promise<string>;

export function FetchApiMessage():Promise<string>;

export function GetVersion():Promise<string>;

export function SearchCredentials(arg1:string):Promise<Record<string, any>>;
