// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCombosFolder() {
  return window['go']['main']['App']['CheckCombosFolder']();
}

export function FetchApiMessage() {
  return window['go']['main']['App']['FetchApiMessage']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SearchCredentials(arg1) {
  return window['go']['main']['App']['SearchCredentials'](arg1);
}
